import { MindMapData } from "@/lib/types/mindmap";

export interface TemplateDefinition {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  data: MindMapData;
}

export const MINDMAP_TEMPLATES: TemplateDefinition[] = [
  {
    id: "brainstorming",
    name: "Lluvia de Ideas Estratégica",
    description: "Estructura radial para explorar conceptos, audiencias y propuestas de valor.",
    icon: "Lightbulb",
    category: "Estrategia",
    data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      grid: true,
      theme: "minimal",
      nodes: [
        {
          id: "root-1",
          label: "Iniciativa Principal",
          description: "Concepto central del proyecto o innovación",
          x: 450,
          y: 300,
          isRoot: true,
          shape: "card",
          color: "indigo",
          fontSize: "xl",
        },
        {
          id: "node-publico",
          label: "Público Objetivo & Segmento",
          description: "Definición clara del cliente ideal",
          x: 100,
          y: 120,
          parentId: "root-1",
          shape: "card",
          color: "purple",
          checklist: [
            { id: "c1", text: "Definir Buyer Persona", completed: true },
            { id: "c2", text: "Entrevistas de validación", completed: false },
          ],
        },
        {
          id: "node-valor",
          label: "Propuesta de Valor Única",
          description: "Diferenciación y ventaja competitiva",
          x: 800,
          y: 120,
          parentId: "root-1",
          shape: "card",
          color: "emerald",
          priority: "HIGH",
        },
        {
          id: "node-canales",
          label: "Canales de Distribución",
          description: "Estrategia de adquisición y tracción",
          x: 100,
          y: 480,
          parentId: "root-1",
          shape: "card",
          color: "blue",
        },
        {
          id: "node-monetizacion",
          label: "Modelo de Monetización",
          description: "Estructura de precios y flujo de ingresos",
          x: 800,
          y: 480,
          parentId: "root-1",
          shape: "card",
          color: "amber",
          checklist: [
            { id: "c3", text: "Pricing recurrente (SaaS)", completed: false },
            { id: "c4", text: "Capacidad Enterprise", completed: false },
          ],
        },
      ],
      edges: [
        { id: "e1", source: "root-1", target: "node-publico", style: "curved" },
        { id: "e2", source: "root-1", target: "node-valor", style: "curved" },
        { id: "e3", source: "root-1", target: "node-canales", style: "curved" },
        { id: "e4", source: "root-1", target: "node-monetizacion", style: "curved" },
      ],
    },
  },
  {
    id: "product-launch",
    name: "Roadmap de Lanzamiento (Go-to-Market)",
    description: "Fases ordenadas desde arquitectura hasta entrega y métricas clave.",
    icon: "Rocket",
    category: "Producto",
    data: {
      viewport: { x: 0, y: 0, zoom: 0.95 },
      grid: true,
      theme: "minimal",
      nodes: [
        {
          id: "root-prod",
          label: "Lanzamiento Versión 1.0",
          description: "Hito maestro de despliegue",
          x: 480,
          y: 280,
          isRoot: true,
          shape: "card",
          color: "indigo",
          fontSize: "xl",
        },
        {
          id: "prod-ux",
          label: "Experiencia & Diseño (UX/UI)",
          x: 140,
          y: 120,
          parentId: "root-prod",
          shape: "card",
          color: "purple",
          checklist: [
            { id: "ux1", text: "Diseño del sistema en Figma", completed: true },
            { id: "ux2", text: "Pruebas de flujo y feedback", completed: false },
          ],
        },
        {
          id: "prod-dev",
          label: "Desarrollo & Arquitectura",
          x: 820,
          y: 120,
          parentId: "root-prod",
          shape: "card",
          color: "blue",
          priority: "URGENT",
          checklist: [
            { id: "dev1", text: "Modelado de base de datos", completed: true },
            { id: "dev2", text: "Integración de APIs y autenticación", completed: true },
            { id: "dev3", text: "Testing de integración", completed: false },
          ],
        },
        {
          id: "prod-mkt",
          label: "Marketing & Comunicación",
          x: 140,
          y: 450,
          parentId: "root-prod",
          shape: "card",
          color: "amber",
        },
        {
          id: "prod-metrics",
          label: "Indicadores de Rendimiento (KPIs)",
          x: 820,
          y: 450,
          parentId: "root-prod",
          shape: "card",
          color: "emerald",
        },
      ],
      edges: [
        { id: "ep1", source: "root-prod", target: "prod-ux", style: "curved" },
        { id: "ep2", source: "root-prod", target: "prod-dev", style: "curved" },
        { id: "ep3", source: "root-prod", target: "prod-mkt", style: "curved" },
        { id: "ep4", source: "root-prod", target: "prod-metrics", style: "curved" },
      ],
    },
  },
  {
    id: "swot-analysis",
    name: "Diagnóstico DAFO / SWOT",
    description: "Análisis estratégico riguroso de factores internos y externos.",
    icon: "Target",
    category: "Estrategia",
    data: {
      viewport: { x: 0, y: 0, zoom: 0.95 },
      grid: true,
      theme: "minimal",
      nodes: [
        {
          id: "root-swot",
          label: "Diagnóstico DAFO Corporativo",
          description: "Evaluación multidimensional",
          x: 480,
          y: 280,
          isRoot: true,
          shape: "card",
          color: "indigo",
          fontSize: "xl",
        },
        {
          id: "swot-f",
          label: "Fortalezas (Internas)",
          description: "Ventajas competitivas sostenibles",
          x: 120,
          y: 110,
          parentId: "root-swot",
          shape: "card",
          color: "emerald",
        },
        {
          id: "swot-o",
          label: "Oportunidades (Externas)",
          description: "Tendencias favorables del mercado",
          x: 840,
          y: 110,
          parentId: "root-swot",
          shape: "card",
          color: "blue",
        },
        {
          id: "swot-d",
          label: "Debilidades (Internas)",
          description: "Áreas críticas de mejora operativa",
          x: 120,
          y: 450,
          parentId: "root-swot",
          shape: "card",
          color: "amber",
        },
        {
          id: "swot-a",
          label: "Amenazas (Externas)",
          description: "Riesgos regulatorios o competitivos",
          x: 840,
          y: 450,
          parentId: "root-swot",
          shape: "card",
          color: "rose",
        },
      ],
      edges: [
        { id: "es1", source: "root-swot", target: "swot-f", style: "curved" },
        { id: "es2", source: "root-swot", target: "swot-o", style: "curved" },
        { id: "es3", source: "root-swot", target: "swot-d", style: "curved" },
        { id: "es4", source: "root-swot", target: "swot-a", style: "curved" },
      ],
    },
  },
  {
    id: "project-wbs",
    name: "Estructura de Desglose de Trabajo (WBS)",
    description: "Organización jerárquica de entregables y paquetes de trabajo.",
    icon: "Network",
    category: "Gestión",
    data: {
      viewport: { x: 0, y: 0, zoom: 0.95 },
      grid: true,
      theme: "minimal",
      nodes: [
        {
          id: "root-wbs",
          label: "Alcance del Proyecto",
          description: "Estructura WBS / EDT",
          x: 480,
          y: 280,
          isRoot: true,
          shape: "card",
          color: "indigo",
          fontSize: "xl",
        },
        {
          id: "wbs-p1",
          label: "1. Fase de Definición",
          x: 140,
          y: 120,
          parentId: "root-wbs",
          shape: "card",
          color: "blue",
        },
        {
          id: "wbs-p2",
          label: "2. Fase de Ejecución",
          x: 820,
          y: 120,
          parentId: "root-wbs",
          shape: "card",
          color: "indigo",
        },
        {
          id: "wbs-p3",
          label: "3. Aseguramiento de Calidad",
          x: 140,
          y: 450,
          parentId: "root-wbs",
          shape: "card",
          color: "amber",
        },
        {
          id: "wbs-p4",
          label: "4. Entrega y Cierre",
          x: 820,
          y: 450,
          parentId: "root-wbs",
          shape: "card",
          color: "emerald",
        },
      ],
      edges: [
        { id: "ew1", source: "root-wbs", target: "wbs-p1", style: "curved" },
        { id: "ew2", source: "root-wbs", target: "wbs-p2", style: "curved" },
        { id: "ew3", source: "root-wbs", target: "wbs-p3", style: "curved" },
        { id: "ew4", source: "root-wbs", target: "wbs-p4", style: "curved" },
      ],
    },
  },
  {
    id: "blank",
    name: "Lienzo en Blanco",
    description: "Espacio de trabajo limpio para estructurar ideas desde cero.",
    icon: "PlusCircle",
    category: "Básico",
    data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      grid: true,
      theme: "minimal",
      nodes: [
        {
          id: "root-blank",
          label: "Idea Principal",
          description: "Doble clic para editar o presiona Tab para añadir ramas",
          x: 480,
          y: 280,
          isRoot: true,
          shape: "card",
          color: "indigo",
          fontSize: "xl",
        },
      ],
      edges: [],
    },
  },
];
