import { MindMapData } from "@/lib/types/mindmap";

export interface TemplateDefinition {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  data: MindMapData;
}

export const MINDMAP_TEMPLATES: TemplateDefinition[] = [
  {
    id: "brainstorming",
    name: "Lluvia de Ideas (Brainstorming)",
    description: "Estructura radial para explorar conceptos, audiencias y propuestas de valor.",
    icon: "Lightbulb",
    category: "Creatividad",
    data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      grid: true,
      theme: "modern",
      nodes: [
        {
          id: "root-1",
          label: "💡 Nueva Gran Idea",
          description: "Concepto central del proyecto o innovación",
          x: 450,
          y: 300,
          isRoot: true,
          shape: "rounded",
          color: "indigo",
          fontSize: "xl",
        },
        {
          id: "node-publico",
          label: "🎯 Público Objetivo",
          description: "Quiénes son nuestros usuarios y qué necesitan",
          x: 100,
          y: 120,
          parentId: "root-1",
          shape: "card",
          color: "purple",
          checklist: [
            { id: "c1", text: "Definir Buyer Persona", completed: true },
            { id: "c2", text: "Entrevistas a usuarios", completed: false },
          ],
        },
        {
          id: "node-valor",
          label: "💎 Propuesta de Valor",
          description: "Qué problema resolvemos mejor que nadie",
          x: 800,
          y: 120,
          parentId: "root-1",
          shape: "card",
          color: "emerald",
          priority: "HIGH",
        },
        {
          id: "node-canales",
          label: "📢 Canales de Difusión",
          description: "Estrategia para llegar a clientes",
          x: 100,
          y: 480,
          parentId: "root-1",
          shape: "pill",
          color: "cyan",
        },
        {
          id: "node-monetizacion",
          label: "💰 Monetización",
          description: "Modelo de ingresos y pricing",
          x: 800,
          y: 480,
          parentId: "root-1",
          shape: "card",
          color: "amber",
          checklist: [
            { id: "c3", text: "Suscripción mensual", completed: false },
            { id: "c4", text: "Plan Enterprise", completed: false },
          ],
        },
      ],
      edges: [
        { id: "e1", source: "root-1", target: "node-publico", style: "curved", color: "#a855f7" },
        { id: "e2", source: "root-1", target: "node-valor", style: "curved", color: "#10b981" },
        { id: "e3", source: "root-1", target: "node-canales", style: "curved", color: "#06b6d4" },
        { id: "e4", source: "root-1", target: "node-monetizacion", style: "curved", color: "#f59e0b" },
      ],
    },
  },
  {
    id: "product-launch",
    name: "Lanzamiento de Producto",
    description: "Hoja de ruta paso a paso desde el diseño y desarrollo hasta el go-to-market.",
    icon: "Rocket",
    category: "Producto",
    data: {
      viewport: { x: 0, y: 0, zoom: 0.95 },
      grid: true,
      theme: "modern",
      nodes: [
        {
          id: "root-prod",
          label: "🚀 Lanzamiento Producto V1",
          description: "Hito principal de despliegue y validación",
          x: 480,
          y: 280,
          isRoot: true,
          shape: "rounded",
          color: "rose",
          fontSize: "xl",
        },
        {
          id: "prod-ux",
          label: "🎨 UX / Prototipos",
          x: 150,
          y: 120,
          parentId: "root-prod",
          shape: "card",
          color: "purple",
          checklist: [
            { id: "ux1", text: "Wireframes en Figma", completed: true },
            { id: "ux2", text: "Pruebas de usabilidad", completed: false },
          ],
        },
        {
          id: "prod-dev",
          label: "⚡ Desarrollo Core",
          x: 820,
          y: 120,
          parentId: "root-prod",
          shape: "card",
          color: "blue",
          priority: "URGENT",
          checklist: [
            { id: "dev1", text: "Arquitectura backend", completed: true },
            { id: "dev2", text: "Frontend interactivo", completed: true },
            { id: "dev3", text: "Pruebas E2E", completed: false },
          ],
        },
        {
          id: "prod-mkt",
          label: "📣 Campaña Marketing",
          x: 150,
          y: 450,
          parentId: "root-prod",
          shape: "card",
          color: "amber",
        },
        {
          id: "prod-metrics",
          label: "📊 Métricas y KPIs",
          x: 820,
          y: 450,
          parentId: "root-prod",
          shape: "card",
          color: "emerald",
        },
      ],
      edges: [
        { id: "ep1", source: "root-prod", target: "prod-ux", style: "curved", color: "#a855f7" },
        { id: "ep2", source: "root-prod", target: "prod-dev", style: "curved", color: "#3b82f6" },
        { id: "ep3", source: "root-prod", target: "prod-mkt", style: "curved", color: "#f59e0b" },
        { id: "ep4", source: "root-prod", target: "prod-metrics", style: "curved", color: "#10b981" },
      ],
    },
  },
  {
    id: "swot-analysis",
    name: "Análisis DAFO / SWOT",
    description: "Evaluación de Fortalezas, Oportunidades, Debilidades y Amenazas.",
    icon: "Target",
    category: "Estrategia",
    data: {
      viewport: { x: 0, y: 0, zoom: 0.95 },
      grid: true,
      theme: "modern",
      nodes: [
        {
          id: "root-swot",
          label: "🎯 Análisis DAFO Estratégico",
          description: "Diagnóstico interno y externo",
          x: 480,
          y: 280,
          isRoot: true,
          shape: "rounded",
          color: "indigo",
          fontSize: "xl",
        },
        {
          id: "swot-f",
          label: "💪 Fortalezas (F)",
          description: "Ventajas competitivas internas",
          x: 120,
          y: 100,
          parentId: "root-swot",
          shape: "sticky",
          color: "emerald",
        },
        {
          id: "swot-o",
          label: "🌟 Oportunidades (O)",
          description: "Factores externos aprovechables",
          x: 840,
          y: 100,
          parentId: "root-swot",
          shape: "sticky",
          color: "blue",
        },
        {
          id: "swot-d",
          label: "⚠️ Debilidades (D)",
          description: "Aspectos internos a mejorar",
          x: 120,
          y: 460,
          parentId: "root-swot",
          shape: "sticky",
          color: "amber",
        },
        {
          id: "swot-a",
          label: "🛡️ Amenazas (A)",
          description: "Riesgos del entorno exterior",
          x: 840,
          y: 460,
          parentId: "root-swot",
          shape: "sticky",
          color: "rose",
        },
      ],
      edges: [
        { id: "es1", source: "root-swot", target: "swot-f", style: "curved", color: "#10b981" },
        { id: "es2", source: "root-swot", target: "swot-o", style: "curved", color: "#3b82f6" },
        { id: "es3", source: "root-swot", target: "swot-d", style: "curved", color: "#f59e0b" },
        { id: "es4", source: "root-swot", target: "swot-a", style: "curved", color: "#f43f5e" },
      ],
    },
  },
  {
    id: "project-wbs",
    name: "Estructura de Proyecto (WBS)",
    description: "Desglose organizado de entregables por fases.",
    icon: "Network",
    category: "Proyectos",
    data: {
      viewport: { x: 0, y: 0, zoom: 0.95 },
      grid: true,
      theme: "modern",
      nodes: [
        {
          id: "root-wbs",
          label: "📁 Proyecto Central",
          description: "Desglose analítico de trabajo (WBS)",
          x: 480,
          y: 280,
          isRoot: true,
          shape: "rounded",
          color: "indigo",
          fontSize: "xl",
        },
        {
          id: "wbs-p1",
          label: "1. Planificación",
          x: 140,
          y: 120,
          parentId: "root-wbs",
          shape: "card",
          color: "cyan",
        },
        {
          id: "wbs-p2",
          label: "2. Ejecución",
          x: 820,
          y: 120,
          parentId: "root-wbs",
          shape: "card",
          color: "indigo",
        },
        {
          id: "wbs-p3",
          label: "3. QA & Pruebas",
          x: 140,
          y: 450,
          parentId: "root-wbs",
          shape: "card",
          color: "amber",
        },
        {
          id: "wbs-p4",
          label: "4. Despliegue",
          x: 820,
          y: 450,
          parentId: "root-wbs",
          shape: "card",
          color: "emerald",
        },
      ],
      edges: [
        { id: "ew1", source: "root-wbs", target: "wbs-p1", style: "curved", color: "#06b6d4" },
        { id: "ew2", source: "root-wbs", target: "wbs-p2", style: "curved", color: "#6366f1" },
        { id: "ew3", source: "root-wbs", target: "wbs-p3", style: "curved", color: "#f59e0b" },
        { id: "ew4", source: "root-wbs", target: "wbs-p4", style: "curved", color: "#10b981" },
      ],
    },
  },
  {
    id: "blank",
    name: "Mapa en Blanco",
    description: "Un lienzo limpio para comenzar a crear desde cero.",
    icon: "PlusCircle",
    category: "Básico",
    data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      grid: true,
      theme: "modern",
      nodes: [
        {
          id: "root-blank",
          label: "🌟 Idea Central",
          description: "Haz doble clic para editar o presiona Tab para crear un nodo hijo",
          x: 480,
          y: 280,
          isRoot: true,
          shape: "rounded",
          color: "indigo",
          fontSize: "xl",
        },
      ],
      edges: [],
    },
  },
];
